name: Run RAGNews and Claremont DB Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests:
    strategy:
      matrix:
        python: [3.11]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Clone and install metahtml
        run: |
          git clone https://github.com/mikeizbicki/metahtml.git
          cd metahtml
          pip install .

      - name: Clone and install bunch
        run: |
          git clone https://github.com/alberttangalbert/bunch.git
          cd bunch
          pip install .

      # New step to make the shell scripts in the "tests" folder executable
      - name: Make shell scripts executable
        run: chmod +x ./tests/*.sh

      # New step to run shell scripts in the "tests" folder
      - name: Run shell scripts
        run: |
          for script in ./tests/*.sh; do
            echo "Running $script"
            bash "$script"
          done